name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Run tests
      run: cargo test --verbose

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Build binary
      run: |
        cargo build --release
        mv target/release/eu4_parser ./eu4_parser

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to EC2
      run: |
        # Copy binary
        sshpass -p "${{ secrets.EC2_PASSWORD }}" scp -o StrictHostKeyChecking=no ./eu4_parser ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_IP }}:~/eu4_parser
        # Set executable permissions
        sshpass -p "${{ secrets.EC2_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_IP }} "chmod +x ~/eu4_parser"
